# Generated by Django 3.2 on 2021-04-20 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(default='fvvfvvf', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
